openapi: 3.0.3
info:
    title: users API
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /openapi3.json:
        get:
            tags:
                - users
            summary: Download ./gen/http/openapi3.json
            operationId: users#/openapi3.json
            responses:
                "200":
                    description: File downloaded
    /users:
        get:
            tags:
                - users
            summary: all users
            operationId: users#all
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/CreateRequestBody'
                                example:
                                    - birth_year: 1993.5607251869492
                                      name: ci5
                                    - birth_year: 1993.5607251869492
                                      name: ci5
                            example:
                                - birth_year: 1993.5607251869492
                                  name: ci5
                                - birth_year: 1993.5607251869492
                                  name: ci5
                                - birth_year: 1993.5607251869492
                                  name: ci5
                                - birth_year: 1993.5607251869492
                                  name: ci5
        post:
            tags:
                - users
            summary: create users
            operationId: users#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            birth_year: 1961.4060702583001
                            name: nne
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateRequestBody'
                            example:
                                birth_year: 1923.9657569924534
                                name: t0q
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                birth_year:
                    type: string
                    example: 1998.6715134042893
                    minimum: 1900
                    maximum: 2022
                name:
                    type: string
                    example: 7pd
                    minLength: 5
            example:
                birth_year: 2008.7441726687148
                name: ll4
            required:
                - name
                - birth_year
tags:
    - name: users
      description: API for users
